site_name: Root docs

nav:
  - Home: index.md
  - Subdirectory docs:
    - Sub Module: '!include ./sub_module/mkdocs.yml'
    - Sub Dir: '!include ./sub_dir/mkdocs.yml'

plugins:
  - monorepo
  - techdocs-core