site_name: 'sample backend'
docs_dir: 'test_dir'

nav:
  - 'home': index.md
  - 'Bug Tracker': '/test_dir/test.md'
  - '2 Bug Tracker': '/test_dir/test.md'

plugins:
  - techdocs-core

watch:
- test_dir
- test_dir_2
