site_name: Root docs

nav:
  - Home: index.md
  - Mappa:
    - Map Annotations: '!include ./map_annotations/mkdocs.yml'
    - Map Controls: '!include ./map_controls/mkdocs.yml'

plugins:
  - monorepo
  - techdocs-core