apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Map Controls
  title: Map Controls
  description: Map Controls Component
  annotations:
    github.com/project-slug: Ryang20718/sample-backstage
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://splunk.com
    title: Dashboards
    icon: dashboard
  - url: https://splunk.com
    title: Test Dashboard
    icon: dashboard
  - url: https://splunk.com
    title: Service Cost Dashboard
    icon: dashboard
  - url: https://splunk.com
    title: Slack Channel
    icon: dashboard
spec:
  type: service
  owner: engineering
  lifecycle: experimental