# schema reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: ci
on:
  workflow_dispatch:
    inputs:
      timeout_minutes:
        description: "Timeout minutes"
        type: string
        default: 1
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  lint: #
    runs-on: ubuntu-latest 
    timeout-minutes: ${{ contains(github.event.pull_request.labels.*.name, 'long ci') && 2 || 1 }}

    steps:
      - name: sleep
        run: sleep 120

      - name: sleep
        run: sleep 120